### ISSUE TITLE
Link error for drlg_l1_test after introduction of Cathedral level generation tests

### ISSUE THREAD

**Issue by tsunamistate** [diasurgical/devilutionX#4643]
**Important information**
Windows 10 / Bisected to c241cae9e304ca9675f442db1325a72da78e77cd / Self-compile with MSVC 2022 v17.2.3

**Describe**
After c241cae9e304ca9675f442db1325a72da78e77cd `drlg_l1_test.exe` linking fails with [LNK2001: Unresolved external symbol](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2001?view=msvc-170) error
Logs from Ninja:
```
  FAILED: drlg_l1_test.exe test/drlg_l1_test[1]_tests.cmake D:/src/devilutionX/build/x64-Debug/test/drlg_l1_test[1]_tests.cmake 
  cmd.exe /C "cd . && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=test\CMakeFiles\drlg_l1_test.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100203~1.0\x86\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100203~1.0\x86\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1432~1.313\bin\Hostx86\x64\link.exe /nologo test\CMakeFiles\drlg_l1_test.dir\drlg_l1_test.cpp.obj  /out:drlg_l1_test.exe /implib:test\drlg_l1_test.lib /pdb:drlg_l1_test.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console  test\test_main.lib  test\libdevilutionx_so.lib  3rdParty\discord\discord.lib  _deps\discordsrc-src\lib\x86_64\discord_game_sdk.dll.lib  vcpkg_installed\x64-windows\debug\lib\manual-link\SDL2maind.lib  vcpkg_installed\x64-windows\debug\lib\SDL2_image.lib  vcpkg_installed\x64-windows\debug\lib\fmtd.lib  3rdParty\PKWare\PKWare.lib  3rdParty\libmpq\libmpq.lib  vcpkg_installed\x64-windows\debug\lib\zlibd.lib  vcpkg_installed\x64-windows\debug\lib\bz2d.lib  3rdParty\libsmackerdec\libsmackerdec.lib  vcpkg_installed\x64-windows\debug\lib\libsodium.lib  _deps\sdl_audiolib-build\SDL_audiolib.lib  vcpkg_installed\x64-windows\debug\lib\SDL2d.lib  _deps\libzt-build\lib\zt.lib  iphlpapi.lib  shlwapi.lib  wsock32.lib  ws2_32.lib  wininet.lib  vcpkg_installed\x64-windows\debug\lib\gtestd.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cmd.exe /C "cd /D D:\src\devilutionX\build\x64-Debug\test && "C:\Program Files\PowerShell\7\pwsh.exe" -noprofile -executionpolicy Bypass -file D:/src/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary D:/src/devilutionX/build/x64-Debug/drlg_l1_test.exe -installedDir D:/src/devilutionX/build/x64-Debug/vcpkg_installed/x64-windows/debug/bin -OutVariable out && cd /D D:\src\devilutionX\build\x64-Debug\test && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -D TEST_TARGET=drlg_l1_test -D TEST_EXECUTABLE=D:/src/devilutionX/build/x64-Debug/drlg_l1_test.exe -D TEST_EXECUTOR= -D TEST_WORKING_DIR=D:/src/devilutionX/build/x64-Debug/test -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX= -D TEST_SUFFIX= -D TEST_FILTER= -D NO_PRETTY_TYPES=FALSE -D NO_PRETTY_VALUES=FALSE -D TEST_LIST=drlg_l1_test_TESTS -D CTEST_FILE=D:/src/devilutionX/build/x64-Debug/test/drlg_l1_test[1]_tests.cmake -D TEST_DISCOVERY_TIMEOUT=5 -D TEST_XML_OUTPUT_DIR= -P "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.22/Modules/GoogleTestAddTests.cmake"""
  LINK Pass 1: command "C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1432~1.313\bin\Hostx86\x64\link.exe /nologo test\CMakeFiles\drlg_l1_test.dir\drlg_l1_test.cpp.obj /out:drlg_l1_test.exe /implib:test\drlg_l1_test.lib /pdb:drlg_l1_test.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console test\test_main.lib test\libdevilutionx_so.lib 3rdParty\discord\discord.lib _deps\discordsrc-src\lib\x86_64\discord_game_sdk.dll.lib vcpkg_installed\x64-windows\debug\lib\manual-link\SDL2maind.lib vcpkg_installed\x64-windows\debug\lib\SDL2_image.lib vcpkg_installed\x64-windows\debug\lib\fmtd.lib 3rdParty\PKWare\PKWare.lib 3rdParty\libmpq\libmpq.lib vcpkg_installed\x64-windows\debug\lib\zlibd.lib vcpkg_installed\x64-windows\debug\lib\bz2d.lib 3rdParty\libsmackerdec\libsmackerdec.lib vcpkg_installed\x64-windows\debug\lib\libsodium.lib _deps\sdl_audiolib-build\SDL_audiolib.lib vcpkg_installed\x64-windows\debug\lib\SDL2d.lib _deps\libzt-build\lib\zt.lib iphlpapi.lib shlwapi.lib wsock32.lib ws2_32.lib wininet.lib vcpkg_installed\x64-windows\debug\lib\gtestd.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:test\CMakeFiles\drlg_l1_test.dir/intermediate.manifest test\CMakeFiles\drlg_l1_test.dir/manifest.res" failed (exit code 1120) with the following output:
D:\src\devilutionX\build\x64-Debug\drlg_l1_test.cpp.obj : error LNK2001: unresolved external symbol "unsigned char devilution::currlevel" (?currlevel@devilution@@3EA)
D:\src\devilutionX\build\x64-Debug\drlg_l1_test.exe : fatal error LNK1120: 1 unresolved externals
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Open DevilutionX in MSVC
2. Click "Build -> Build All" in the top menu or press Ctrl-Shift-B
4. See link error

**Expected behaviour**
All tests are successfully compiled
